### ISSUE TITLE
Headless rendering example

### ISSUE THREAD

**Issue by Capytara** [nanoqsh/dunge#9]
Hi nanoqsh. Could you provide an example of headless rendering? I saw you mentioned "can simply draw a scene directly to the image in RAM," but I don't seem to find the relevant API. Thank you very much for developing dunge, it's really awesome!

**Comment by nanoqsh** [comment]
@Capytara
Are looking for something like this?
https://github.com/nanoqsh/dunge/blob/main/dunge/tests/triangle_vertex.rs

Here is an example that works without a window and renders the final frame into an image. Also there is more similar examples in the tests directory

**Comment by Capytara** [comment]
Thank you, this is indeed largely what I wanted. However, it seems that dunge cannot directly render to a `TextureView`? I mean, I currently have a `wgpu::TextureView`, which might be a surface or an editor viewport. I hope that dunge can render directly to the `texture_view`, instead of first rendering to an image and then copying it.

**Comment by nanoqsh** [comment]
Use can render with context's `draw_to` in any target [`T: AsTarget`](https://docs.rs/dunge/latest/dunge/trait.AsTarget.html).
Currently it may be a drawable texture or a render buffer (two drawable textures with color and depth attachment).

In particular, you can render something directly into a texture like this:
```rust
let cx = dunge::context().await?;
let data = TextureData::empty(TEXTURE_SIZE, Format::SrgbAlpha)
    .expect("non-zero size")
    .with_draw()  // set render flag to render something into texture
    .with_bind(); // set bind flag to use the texture directly in a shader

let render_texture = cx.make_texture(data);

// now you can render into this
let draw = /* some impl Draw instance https://docs.rs/dunge/latest/dunge/trait.Draw.html */
cx.draw_to(&render_texture, draw);

// and you can use `render_texture` as the shader binding
#[derive(Group)] // make a new bind group
struct Map<'a> {
    texture: BoundTexture<'a>,
    sampler: &'a Sampler,
}

let sampler = cx.make_sampler(Filter::Nearest);
let map = Map { // create the group instance
    texture: BoundTexture::new(&render_texture),
    sampler: &sampler,
};

// then you can bind this group instance in some shader and use `render_texture` in it
```

Unfortunately I don't have many examples of this, but I have an example of rendering something into an intermediate render buffer: https://github.com/nanoqsh/dunge/blob/main/examples/ssaa/src/lib.rs
